config/waybar/config

Polling interval for battery is declared twice, removed one of them.

chore: removed duplicated key in waybar battery config

---

config/hypr/hyprland.conf
install/hyprlandia.sh
install/nvidia
install/nvidia.sh

This PR attempts to implement automatic NVIDIA detection in Omarchy. For cards newer than the GTX 1000 series, nvidia-open-dkms should be used, while older cards should use nvidia-dkms, along with additional packages for a more seamless NVIDIA + Hyprland setup.
This is untested, please test it and let me know!
You can try to install with:
`wget -qO- https://raw.githubusercontent.com/Kn0ax/omarchy/refs/heads/patch-install/boot.sh | bash
`

Nvidia support for omarchy 

---

default/hypr/bindings.conf

When hitting SUPER + space several times, a new instance of wofi is launched each time and they stack upon each other. This change uses a file lock to prevent starting several instances of wofi.
Thanks to everyone from this thread
https://www.reddit.com/r/archlinux/comments/m327pt/prevent_wofi_from_stacking_up/

Prevent wofi from stacking up

---

default/bash/aliases

This alias makes it easier to search for packages from the AUR or main repository and get information about them.

Add yayf alias for easy package search

---

config/nvim/lua/plugins/theme.lua

Additionally, check if the current theme is accessible and loadable else, fallback to a default theme as to not break the theme.
fixes: #36

Be able to switch to current theme for neovim

---

bin/omarchy-fingerprint-setup

Without setting the username the fprintd will set the fingerprint to the root user

username needs to be set for fprintd-enroll

---

default/bash/shell
install/3-terminal.sh
migrations/1751821819.sh

Enable bash-completion by default:
- First check if `BASH_COMPLETION_VERSINFO` is defined. That means bash completion has already been sourced, perhaps by an earlier configuration.
- Then if `/usr/share/bash-completion/bash_completion` exists, to avoid breaking setups where `bash-completion` is not installed.
- Install `bash-completion` by default.

Enable bash-completion by default

---

install/nvidia.sh

The script attempted to perform driver selection by echoing the `$gpu_info` variable, but the variable had not yet been populated
with the output from the `lspci` command.
This resulted in the `if` condition always failing and the driver package incorrectly defaulting to `nvidia-dkms` for all hardware.
This commit moves the `gpu_info` assignment to occur before it is referenced, restoring the correct behavior.

fix(detect): Correctly assign gpu_info before use

---

config/waybar/config
config/waybar/style.css
themes/catppuccin/mako.ini
themes/everforest/mako.ini
themes/gruvbox/mako.ini
themes/kanagawa/mako.ini
themes/nord/mako.ini
themes/tokyo-night/mako.ini

Adds a simple DND option that can be toggled by clicking the bell icon to the default Waybar config.

Add DND option to Waybar

---

bin/omarchy-power-menu
config/waybar/config
config/waybar/style.css

This PR adds a convenient power menu, providing users with quick access to essential power options, directly from Waybar. 
- **Power Menu Script**: Added `bin/omarchy-power-menu` - a bash script that displays a wofi-based power menu
- **Waybar Integration**: Added power menu button to the Waybar interface
- Interactive power menu using wofi as the display manager
- Provides 5 essential options with intuitive icons:
- Power Off (`systemctl poweroff`)
- Restart (`systemctl reboot`) 
- Sleep (`systemctl suspend`)
- Logout (`hyprctl dispatch exit`)
- Lock (`hyprlock`)
- Added `custom/power-menu` module to the modules-right array
- Configured power menu button with power icon
- Set up click handler to execute the power menu script
- Extended CSS styling to include `#custom-power-menu`
- …

Add Power Menu to Waybar

---

default/hypr/autostart.conf
default/hypr/bindings.conf
install/hyprlandia.sh
install/nvidia.sh
migrations/1751848081.sh

This PR adds support for https://github.com/hyprwm/hyprsunset, a blue light filter daemon for Hyprland that allows users to adjust their screen's color temperature for reduced eye strain.
After installation, users can adjust their screen's color temperature using the Ctrl key combined with their laptop's brightness keys. This provides a convenient way to reduce blue light exposure, especially useful during evening hours.

Add blue light filter

---

bin/omarchy-power-menu
config/wofi/omarchy-power-menu.css
default/hypr/bindings.conf

Made some improvements to the Waybar Power Menu as suggested in https://github.com/basecamp/omarchy/pull/65#issuecomment-3042850831.
- **Removed the search bar**
- **Add shortcuts for each option**
**`bin/omarchy-power-menu`**
- Added shortcuts in parenthesis.
- Increased width and reduced height to better fit the shortcuts.
- Linked to a new stylesheet, specific to the power menu. This was done to prevent style conflicts for other wofi menus e.g the Application index and launcher.
**`config/wofi/omarchy-power-menu.css`(new file)**
- Styles specific to the power menu. I based this off the current wofi styles.css.
- CSS trick to hide the search for the power menu (this is the best I could find). There is also a hide-search flag you can add to the wofi config file, however, this also …

Waybar Power Menu - Remove Search and Add Shortcuts

---

bin/omarchy-refresh-waybar

Small addition to `omarchy-refresh-waybar`. Added a gum confirm dialog before overwriting the user's Waybar configuration. The prompt warns users that their current settings will be replaced with Omarchy defaults, preventing accidental loss of customizations.

Add gum confirm to omarchy-refresh-waybar

---

install/network.sh

When archinstall is run using an ethernet connection, iwd will not be
installed. Explicitly install and enable the service

install: explicitly install iwd

---

bin/omarchy-battery-monitor
config/systemd/user/omarchy-battery-monitor.service
config/systemd/user/omarchy-battery-monitor.timer
install/power.sh
migrations/1752168292.sh

Implementation of the systemd timer-based battery monitoring, that i described in:
https://github.com/basecamp/omarchy/issues/59  
in the issue i made it seem like i wanted to do the simple solution with bash script, but i backed tracked on this idea and went with the time based systemd approach.
Might do the udev for my own setup, if i care later..
- Implements systemd timer-based battery monitoring
- Sends notification at 10% battery level
- uses /run/user/$UID/omarchy_battery_notified to save the state, if notification has been sent to avoid spamming.
- Only enables on battery-powered systems
-- Reviewer focus: grep and sed command or pray that they are okay. 
--- to test set either have patience or set the threshold higher and reload service? (not sure if just goes with what ever is …

add low power notfication issue #59

---

config/waybar/config
config/waybar/style.css

This adds an expanding/collapsing group containing tray app icons to Waybar. I know you want to keep the bar minimal, so even if you don't want to use it for 'tray' icons, it might be a useful way to let you add more to the bar without cluttering it. I'm thinking things like #63 
Poor quality preview:
[tray.webm](https://github.com/user-attachments/assets/26e0943e-a434-494f-9de0-42972cc64880)

Add collapsing tray to waybar

---

bin/omarchy-fingerprint-setup

Many laptops use a Synaptics fingerprint reader so this PR adds Synaptics to the check to see if one exists

Add Synaptics support to the fingerprint setup script

---

themes/matte-black/alacritty.toml
themes/matte-black/btop.theme
themes/matte-black/neovim.lua

This pull request introduces several visual improvements to the Matte Black theme to ensure greater color consistency across different applications.
-  Alacritty: The Alacritty configuration has been updated to use the same color palette as the rest of the Matte Black theme.
-  Neovim: The Neovim theme file has been updated with extensive color overrides. The syntax highlighting and UI elements are now in line with the Matte Black palette.
As discussed, these changes help to unify the look and feel of the Matte Black theme. 
Let me know if any further adjustments are needed!

Update and Refine Matte Black theme for consistency

---

default/gpg/dirmngr.conf
install/4-config.sh
migrations/1752535341.sh

There are multiple reports of ubuntu keyserver being unreliable for various regions, so this adds additional fallback keyservers.
This is still failing for me on spotify as it says their key isn't found - maybe their latest key hasn't propagated fully yet? 
I'm not sure what the optimum order of keyservers should be, but this seems like a good starting point.
This will fix #173 
Note: Spotify does work now when I just tried it - def just hadn't propagated

Additional keyservers

---

bin/omarchy-update

This is a minor follow-up to dcc40719793d52d43698108a0b0784c2f3b48655 (from #204) to leverage the [`--autostash` flag of `git pull`](https://git-scm.com/docs/git-pull#Documentation/git-pull.txt---autostash) which does the same thing we were doing in three separate commands.
Importantly, this also avoids the possibility of popping something from the stash that `omarchy-update` didn't actually stash. In other words, if the initial `git stash` was a no-op (because there were no changes in the working tree), it's actually not desirable for `omarchy-update` to `git stash pop` at the end, since that potentially pops something the user had manually stashed (we only want `omarchy-update` to pop its own stash entry). Using `--autostash` handles this correctly.

Use `git pull --autostash` in `omarchy-update`

---

install/docker.sh
install/login.sh
migrations/1752797704.sh

Recently, some users have experienced some long black screen loading times after the plymouth loader dismisses. This time is typically related to the system awaiting network-online.target status before it can move on to loading a graphical interface. 
This patches this in 2 ways:
1. Prevents the plymouth loader from dismissing until after multi-user.target meaning that even if we do get hung up, you'll be on the plymouth loader the whole time.
2. Prevents Docker (the root cause) from blocking progression of the boot sequence until network-online.target is achieved. 
Everything still boots fine and will finish up while in the GUI. 
I tested this by adding a service that attached to network-online.target and just did a `sleep 30`. This meant I always had a 30sec delay in boot, and even …

Improve boot times

---

bin/omarchy-update

If the worktree has conflicts after `omarchy-update` applies the user's changes from the autostash, we should reset them before proceeding to ensure we are in a working state. When there are conflicts, git still keeps the stash entry, so the user will still be able to manually re-pop the stash and resolve the conflicts after `omarchy-update` has finished.

Reset any stash changes before proceeding if there were conflicts

---

config/waybar/config.jsonc
default/hypr/windows.conf
install/desktop.sh

This is a proposal to replace `pavucontrol` with [`wiremix`](https://github.com/tsowell/wiremix).
I prefer Wiremix because it is easier to control with the keyboard and I think it is a better fit for Omarchy. 
With `enter` on the first screen you can change the output for an application.
Some default keybindings might be a bit confusing. `d` or right click to change the default for example.
With `?` you can see the shortcuts. 
For now I kept the default values and did not add a separate config.
A preview:

Replace pavucontrol with wiremix

---

install/xtras.sh
migrations/1752983008.sh

The zoom package was removed in commit 72e863f. This PR restores it.
If the removal was intentional, maybe we should also remove the Zoom.desktop file and update the manual.

Restore zoom package installation

---

bin/omarchy-update

Previously, `omarchy-update` used the timestamp of the most recent git commit to determine which migrations are "new" and should be executed.
Unfortunately, that strategy can (and did: https://github.com/basecamp/omarchy/issues/187) fail in certain scenarios. If a migration was generated at time T1 but not merged until time T3, and meanwhile omarchy's `master` branch was updated to a new release with commit timestamp T2 (where T1 < T2 < T3), then anyone who runs `omarchy-update` between T2 and T3 would end up with `last_updated_at` equal to T2; thus, on their next `omarchy-update` it would fail to detect the migration with timestamp T1 as a "new" migration that should be executed.
This PR changes the strategy for detecting "new" migrations to avoid that problem. Rather than recording the …

Fix detection of "new migrations" in `omarchy-update`

---

default/hypr/envs.conf

Provides `GDK_BACKEND` and `QT_QPA_PLATFORM` as described in the [hyprland documentation](https://wiki.hypr.land/Configuring/Environment-variables/#toolkit-backend-variables). Without this certain applications may fail to start. 
```text
INFO         | Warning: Could not find the Qt platform plugin "wayland" in "/home/blaz/Android/Sdk/emulator/lib64/qt/plugins" (:0, )
INFO         | Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: linuxfb, offscreen, vnc, minimal, xcb.
```

[envs.conf]  - Provide Toolkit Backend fallbacks

---

install/detect-keyboard-layout.sh

This PR addresses #272
Reads the keyboard layout and variant from /etc/vconsole.conf (set by archinstall) and updates ~/.config/hypr/hyprland.conf with the correct values.
Tested with us, us-acentos, and br-abnt2.

Detect and apply keyboard layout configured during Arch installation

---

bin/omarchy

Add MariaDB as an option for the Docker databases.

Add MariaDB to Docker databases

---

default/hypr/bindings/media.conf

- Update the media bindings to only display on the currently focused monitor.
- sway-osd can also do playerctl

Update media bindings to only display OSD on the focused display

---

bin/omarchy-cmd-screenrecord
bin/omarchy-cmd-screenshot

Update to the `omarchy-cmd-screenrecord` and `omarchy-cmd-screenshot` commands to allow a user to set the output directory of both while maintaining the default.

allow override of screenshot/screenrecord output

---

default/bash/init

- Update fzf completion source path from `/usr/share/bash-completion/completions/fzf` to `/usr/share/fzf/completion.bash`

Fix fzf completion path for Arch Linux

---

bin/omarchy-cmd-screenrecord
bin/omarchy-cmd-screenshot

If you install Arch with non-US locale the Videos and Pictures directories might not exist. Instead you will have directories with localized names. Those names can be extracted from `~/.config/user-dirs.dirs` if package `xdg-user-dirs` is installed.

take into consideration xdg dirs for screenshot and screen recording

---

bin/omarchy-refresh-applications
install/config/config.sh
migrations/1752983008.sh

This PR is intended to finalize the bare install of Omarchy. DHH doesn't want a ton of energy to be put into the bare version, as it already was a concession that kind of goes against the point of the project. However, he does want some things improved.
Once a bare install is run, there is no way for any migrations ran after updates to actually know that the user used the bare install. This results in situations where Zoom is installed on updates, just as one example, even though the user never wanted that in the first place.
In fact, there is just no way period to see if Omarchy was installed bare. This PR adds a `bare.mode` file to `~/.local/state/omarchy/` when installed in bare more to address that problem. 
To run something in a shell script only if _not_ bare, wrap it in an if block …

Improvements to Bare Install

---

config/fastfetch/config.jsonc
migrations/1753683888.sh

This PR adds a line to the FastFetch (About) display about the current Omarchy version.
Easy way for users to check what version they're on.
- Plus, a migration script.

Display current Omarchy version in Fastfetch

---

default/hypr/windows.conf

The existing rule`windowrule = center, class:steam`  (introduced in commit 46d135025e64d6e19e599c996d0bbc9e5cf457d9) causes Steam's popup windows (like right-click context menus) to be centered on the screen, which impacts the user experience.
This PR restricts the rule to only apply to the main Steam window by matching both class and title. As far as I could test, only the main Steam window has a title and is still centered correctly with this change.

Fix: restrict Steam centering to only the main window

---

migrations/1752091783.sh

In migrations/1752091783.sh,
path to login.sh requires update to new location.

Update location of sourced install script

---

default/bash/envs

We've already got `bat` installed, but it's not using the theme set in Alacritty (this is supposed to be Catppuccin):
But by setting `BAT_THEME=ansi`, it is!
This PR just adds that ENV var to the `default/bash/envs` file. I don't think it needs a migration as this file is updated when the repo is updated?

Adds ENV var to get `bat` using the system theme

---

default/plymouth/omarchy.script
migrations/1754108993.sh

This solves the issue we've seen where in multi-monitor setups, the login prompt will be drawn off to the bottom right of the screen. Credit to @RaphaelKimmig for helping me identify the issue via PR #419.
This also resolves the issue where people with passwords > 21 characters would see bullets drawn outside of the password field.
Fixes #142. Fixes #355.

Fix Plymouth login positioning in multi-monitor setups + limit password from overflowing

---

config/waybar/style.css
migrations/1754133148.sh

Adds opacity to the workspace indicators on waybar, if the workspace is empty. Makes the indicator appear dimmer for empty workspaces so they can be identifed from workspaces that have windows. Purely cosmetic UI tweak.

Opacity for indicators of empty waybar workspaces

---

config/walker/config.toml

This pull request adds Vim-style navigation support to walkers default configuration as well as retaining the original navigation in Omarchy.
I noticed we can use `j` and `k` in the Omarchy TUI but not when choosing themes and at the power menu and thought it would add a small quality of life improvement for users who prefer Vim bindings whilst maintaining some consistency.

Add Vim-style j/k navigation to walker config

---

boot.sh

When testing updates prior to submitting a PR, it's nice to be able to do a full install. This would allow something like `wget -qO- https://omarchy.org/install | OMARCHY_REPO=ryanrhughes/omarchy OMARCHY_REF=test bash` to pull from my own repo on a test branch without jumping through as many hoops.

Make initial install repo configurable

---

install/desktop/desktop.sh

When connecting an Android phone via USB, it's not appearing in Nautilus despite the correct file transfer settings being selected on the device. This prevents users from accessing their phone's storage through the file manager.
To fix this, we should install the `gvfs-mtp` package. This provides the necessary **Media Transfer Protocol (MTP)** support for Nautilus, allowing Android devices to be recognized and mounted properly.
---
See the Arch Wiki for more details: [Media Transfer Protocol](https://wiki.archlinux.org/title/Media_Transfer_Protocol#File_manager_integration)

Install `gvfs-mtp` to enable Android MTP file transfer support

---

bin/omarchy-theme-remove

Theme remove menu selection didn't have functional arrow keys for the selection items, think it is just a command piping issue, fixed with the below.

small fix for theme-remove menu selection items

---

bin/omarchy-lock-screen
bin/omarchy-menu
config/hypr/hypridle.conf
migrations/1754679822.sh

Because 1password doesn't integrate well with the hyprland session, it doesn't allow locking on idle.
This script ensures that an open 1password vault will be locked whenever the screen is locked.

Lock 1password on screen lock

---

bin/omarchy-pkg-install
bin/omarchy-pkg-remove
default/bash/aliases

This pull request slightly improves the usability of omarchy-pkg-install/remove and yayf by adding a more comfortable spacing to the preview panel (50%) with line wrapping and some keybindings:
- alt-p: toggle preview panel
- alt-j/alt-k: scroll line by line in the preview panel
- alt-d/alt-u: scroll half a page in the preview panel
I reserved alt+ for the preview panel and ctrl+ for the list, which by default already supports ctrl+j/k.

Package manager usability improvements

---

bin/omarchy-install-dev-env

As discussed on the #594 PR this is the version using Arch packages repository instead of downloading PHP binary on the user home.

Use system wide package manager to install a package and install Laravel for the current user.

---

applications/About.desktop
bin/omarchy-version

User changes font and size for terminal, often larger fonts.
This affects styling and font size of About as it uses same terminal. About is something user wants to look or show, so if big logo of OS, and format of spec and versions, looks messy. It is not beautiful.
This will set the size (may vary with different font a bit) of fastfech out put in the float. I have defaulted to size 9 but please changae if you feel somehting else is better.
This was one of the most asked questions how to fix, in the chat, after font change menu introduced.
Now, tried to override float size in ~/.config/hyprland/system-override.conf, with larger float size, and sourced in hyprland.conf. It did not work. Manually fixed missing " ," (already fixed in v1.12.1) in default hypr config (system.conf),  and …

About.desktop fixed font size

---

install.sh
install/preflight/guard.rb

We keep having folks trying to install Omarchy on something else than a fresh Arch installation.

Omarchy is exclusively for vanilla Arch without Gnome or KDE installed

---

default/hypr/apps.conf
default/hypr/apps/1password.conf

This PR adds the ```noscreenshare``` windowrule to 1Password.
This windowrule blacks out the window when screen sharing, preventing accidentals leaks.
From Hyprland wiki:

Add noscreenshare windowrule to 1password

---

bin/omarchy-lock-screen

My previous script here had an error, it would only lock 1password once the lockscreen was terminated.
We still want to lock the screen first, but we mustn't wait for hyprlock to exit. 
I've also backgrounded the 1password lock call, no need to wait for that either.

Lock 1password right away, not after unlock

---

bin/omarchy-cmd-screenrecord

Screen recording with ALT+PrtScreen was failing on Intel graphics due to VAAPI compatibility issues with wl-screenrec. This change adds Intel graphics detection to use wf-recorder instead, which works properly with Intel hardware.
Changes:
- Add Intel graphics detection in omarchy-cmd-screenrecord  
- Use wf-recorder for Intel graphics instead of wl-screenrec
- Preserve existing behavior for NVIDIA (wf-recorder) and AMD/other (wl-screenrec)

Fix screen recording on Intel graphics

---

install/preflight/gum.sh

One more minor tweak. `yay` is only available after the `aur.sh` step, so `pacman` must be used to install `gum` at the very beginning of `install.sh` preflight section.

Use `pacman` instead of `yay` to install `gum`

---

install/preflight/aur.sh

I think it would be great to be able to choose to use the standard AUR repo via an env flag. Related: #727

Allow disabling the chaotic AUR repo via env flag

---

bin/omarchy-menu-keybindings

This PR adds additional key modifier combinations to the `omarchy-menu-keybindings` script. 
While these aren't currently used directly in the Omarchy code, when the user adds custom bindings they are not properly displayed by the omarchy-menu-keybindings script.
The added combinations are:
```
SUPER + ALT
SUPER + SHIFT + ALT
SUPER + CTRL + ALT
SUPER + SHIFT + CTRL + ALT
```

Add missing modifier combinations to omarchy-menu-keybindings

---

install/development/firewall.sh

I have been running the installation via `ssh`, but there is currently an error when enabling `ufw`. The issue is that `ufw` prompts whether you are sure, because `ssh` may disconnect, and then aborts because no response is given.
Adding the `--force` flag bypasses the prompt, and allows the entire installation complete via `ssh`. I can also confirm, having tested, that no disconnect occurs.
Details on this flag are [documented here](https://man.archlinux.org/man/ufw.8#REMOTE_MANAGEMENT).

Add `--force` when enabling ufw to bypass prompt

---

config/walker/config.toml
migrations/1754929737.sh

This will close the launcher after 60 seconds of inactivity.  
Found that if the launcher was left open the screensaver would open in a new terminal window rather than the entire screen.  
I chose 60 seconds as that seems reasonable (and needs to be under the 150 seconds before the screensaver kicks in)
Fixes https://github.com/basecamp/omarchy/issues/680
There was some timeout bugs upstream I found and fixed to help with this https://github.com/abenz1267/walker/pull/396
https://github.com/abenz1267/walker/issues/393

Add 60 second inactivity timeout to Walker launcher

---

install/desktop/desktop.sh
migrations/1755548643.sh

Hi,
Last week, a fix was added to make the screen recorder work with Intel GPUs. However, wf-recorder is missing, since there is a check during the initial setup.
This PR adds the missing package.

Add missing package for Intel Graphics Card based device

---

default/hypr/bindings/tiling.conf

Adds binding for the "reverse" action of window cyclenext for active workspace. Shortcut for when many windows are in view.

add reverse window cycling with cycleprev

---

install/development/nvim.sh

On running `archinstall`, users often install nvim as an additional package (so they have an editor for troubleshooting), but later find that after running the omarchy install script, their setup is missing the expected LazyVim configuration because the current installer considers default nvim without any configuration as already setup. 
To fix this, we can include a check for absence of `~/.config/nvim` in addition to the check for absence of nvim, and setup LazyVim in either case. This applies the full config when nvim is present but has no configuration files, thereby avoiding overwriting existing setups.
This should ensure users don't end up with a default neovim environment unexpectedly and have to look through the script to find `~/.local/share/omarchy/config/nvim`, like I did.

Run omarchy lazyvim install if nvim present without any config

---

themes/ristretto/alacritty.toml

The current version renders black and bright black like so.
Having these colors this close to the background makes them practically unusable. 
I've picked some grays from the monokai pro ristretto nvim colors to make the contrast more pronounced.

 improve black contrast in ristretto alacritty theme

---

config/fcitx5/conf/xcb.conf
migrations/1755139080.sh

Solves #483
This avoid the fcitx5 default behaviour that overrides the xkb layout on boot, overriding the layout set by hyprland configs. A explained in [this comment](https://github.com/basecamp/omarchy/issues/483#issuecomment-3186453764).
1. Added a migration to fix the current installations on update
2. Added the fcitx5 config for the new installations

fix: Avoid fcitx5 override of xcb keyboard layout

---

boot.sh

Ref: https://github.com/basecamp/omarchy/issues/216#issuecomment-3217919769
This will allow us to change GitHub's default branch to `dev`, so that PRs will target the correct branch by default, but new installations will still default to using the stable `master` branch.

Default `OMARCHY_REF` to `master` in boot.sh

---

bin/omarchy-setup-dns

Follow-up to #752 implementing @dhh's request to ensure network interfaces properly respect DNS configuration.
The script now configures systemd-networkd to prevent DHCP from overriding custom DNS settings:
- Sets UseDNS=no for both DHCPv4 and IPv6AcceptRA when using Cloudflare/Custom DNS
- Removes UseDNS=no when using DHCP mode
- Only affects primary interfaces (wlan0, ethernet), excludes docker/loop interfaces
This ensures the DNS configuration chosen by the user is actually respected by all network interfaces.

Configure network interfaces to respect DNS settings

---

bin/omarchy-setup-dns

Replace Google DNS with Quad9 as the fallback DNS provider for better privacy consistency.
Users choosing Cloudflare likely value privacy, so Quad9 (9.9.9.9, 149.112.112.112) is a more appropriate fallback than Google.
As discussed in #752 and approved by @dhh in #1043.

Use Quad9 as fallback DNS for better privacy

---

config/fastfetch/config.jsonc

The fastfetch configuration is missing some elements because they’re simply not present in the system. One of these is the DE, which was previously used as the header for the second block in _Software_.
Since there’s no suitable replacement, I suggest using an "Omarchy" label instead—one that reflects all the customizations applied to the base Arch system.
Here is the version without DE and with the two flying lines: 
Here is the proposed fixed version:

Use Omarchy version as fastfetch header

---

bin/omarchy-webapp-remove

This tiny change to the gum command makes the removal process much clearer for selected Web Apps being sent on their one-way journey.
Current:
New:

UX: Change webapp removal selection icons

---

default/hypr/bindings/utilities.conf

Seems like the description was made for something else.
Should be easier for people to find using `SUPER + K` now.

Fix emoji picker description

---

bin/omarchy-tui-remove
bin/omarchy-webapp-remove

Greetings!
I've noticed in 2.0 that the multiple select and the script itself do not work with multiple word app name inputs, e.g. "Google Photos" but rather tries to remove both "Google" and "Photos" in that case.
Attempt to fix in this PR.

fix multiple word app names

---

install/config/detect-keyboard-layout.sh

Keyboard is wrongly set after install because the config moved to a dedicated input.conf so no substitution is done.
Fix that and use https://github.com/omacom-io/omarchy-configurator/pull/14 in a new iso and the locale will be ok from  start to finish.

Fix keyboard layout at install

---

bin/omarchy-menu
config/waybar/config.jsonc

Bothered me that the power profile setting was so hidden away, so I made it pop up by clicking the battery icon. :) At the very least, opening the power profiles list should be in the go_to_menu function anyway. 
Thanks for omarchy!

make clicking on the battery icon open the power menu

---

bin/omarchy-snapshot
migrations/1756153445.sh

Not everyone has used the default BTRFS layout, or has the same names for their snapper configs. This commit lists out the existing snapper configs and loops over them to create snapper snapshots.
I only had a `root` config and the omarchy update script was breaking showing: `unknown config`.
This commit fixes the issue for me and should result in the existing behavior for everyone else.
#1216

Don't hardcode snapper configs, read the config list first

---

default/hypr/windows.conf

https://github.com/basecamp/omarchy/issues/1269
Prevent screensaver/lockscreen from activating during games and such

Set hypridle exception for fullscreen apps

---

config/hypr/bindings.conf

`unbind = SUPER, Space` will not work, but `unbind = SUPER, SPACE` will

Fix comment formatting for key unbinding example

---

migrations/1755109182.sh
migrations/1756491748.sh

Fixes #1246
Reopening the DNS fix since the previous PR #1271 got closed accidentally.
Migration 1755109182.sh only fixed resolved.conf but didn't remove UseDNS=no from network files, causing DNS to revert to Cloudflare after reboot.
This adds:
- Fix to migration 1755109182.sh to remove UseDNS=no from network files
- New migration 1756491748.sh for users who already ran the old version
Both now match what omarchy-setup-dns DHCP does.
Tested and confirmed it fixes the issue.

Fix DNS migration to handle UseDNS=no in network files

---

install/packages.sh
migrations/1756556731.sh

GNOME Files on Omarchy did not handle `smb://` URIs by default (common for Synology NAS).
Add `gvfs-smb` to package list.
This includes additional dependencies:
- `samba`
- `smbclient`
- `cifs-utils`
Files → Network → Server address accepts `smb://<IP>` and mounts shares.

Add gvfs-smb so GNOME Files (Nautilus) can handle smb:// URIs.

---

bin/omarchy-migrate

Failed migrations can be now be skipped by a prompt. This means that if a migration is "stuck" then a user can opt to store it in a separate skipped directory. Skipped migrations will be considered for the purposes of running the pending migrations, however in future, we can allow the user to run their skipped migrations with a flag.
To allow the script to continue and prompt for failed migrations, the `set -e` has been removed. A manual check on the exit code is used instead.

Allow failed migrations to be skipped

---

bin/omarchy-menu

As well as installing the `emacs-wayland` package, we enable and start the `emacs` systemd service. A GUI Emacs client can then be started using e.g. `emacsclient -c`.

chore: Add Emacs to editor install menu

---

bin/omarchy-install-docker-dbs

This PR addresses an issue where users reported confusion on [Discord](https://discord.com/channels/1390012484194275541/1390012487000395859/1410684011025535067) when they didn’t select any databases to install in the Omarchy database installation script. Previously, if no databases were selected (e.g., by pressing Esc or Enter without choosing an option), the script would silently return to the main menu.
This PR adds a message when no selection is made.

fix: Add Feedback when no Docker DB Selected

---

bin/omarchy-menu

I tried to install `Minecraft` through Omarchy's menu, however it fails with the following error message:
error: target not found: minecraft-launcher
This occurs because, [according to Arch's documentation, the package is available through AUR](https://wiki.archlinux.org/title/Minecraft#Installation) rather than the official repositories.

Fix Minecraft installation

---

default/hypr/bindings/utilities.conf

Currently, toggling Top Bar from the menu kills Waybar, while toggling via the keyboard shortcut sends SIGUSR1. This mismatch is confusing: not only two code paths, but after using the menu, the shortcut no longer works because Waybar is gone.
This PR fixes this.

Unify top bar toggle: always pkill waybar

---

default/hypr/apps/browser.conf

Ensures that any browser apps opening youtube or its subdomains (e.g. tv.youtube.com) have no transparency.  This regex matches examples like:
tv.youtube.com
music.youtube.com
kids.youtube.com
youtube.com
but not:
notyoutube.com

Match youtube subdomains in opacity windowrule

---

bin/omarchy-cmd-screenshot

Without the --freeze (-z) flag in hyprshot, the target screen or application continues to respond to events during capture.
This means the actual screenshot is taken only after the selection area has been drawn. As a result:
- Menus, context menus, or tooltips may disappear before they can be captured, since the application reacts to the PRINT key while the area is still being selected.
- Capturing a specific frame from a video call, animation, or any other moving content is unreliable.
The --freeze option solves this by pausing updates during capture, ensuring the screenshot includes the exact elements visible at the moment of triggering.

Add --freeze option to screenshot command for improved capture stability

---

config/hypr/input.conf

I believe this is a sensible default for those that have keyboards with num pads. Whenever I want to enter a number I reach for the numpad, just to realize that numlock is off and it doesn't do what I expect it.

Enable numlock by default in input configuration

---

default/hypr/apps/browser.conf

It wouldn't recognize Firefox with this kind of regex so browser was still transparent when it shouldn't

change firefox class regex

---

themes/ristretto/alacritty.toml

The cursor and text color in the ristretto alactritty theme config are currently the same. This change sets the cursor text color to match the background color. This should be the expected behavior.

fix: make character under cursor readable in alacritty ristretto theme

---

bin/omarchy-install-dev-env

While working in a non-trivial feature, I needed debugger support.
Since Xdebug is the official PHP debugger, is available in Arch's official repositories, and is trivial to configure, it makes sense to include it in the PHP development environment.
This addition improves the overall development experience for PHP developers by enabling easier inspection and troubleshooting.
With this PR, the debugger now shows up as an enabled extension:
```diff
$ php -v
PHP 8.4.12 (cli) (built: Aug 27 2025 06:23:40) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.4.12, Copyright (c) Zend Technologies
+++    with Xdebug v3.4.4, Copyright (c) 2002-2025, by Derick Rethans
```
As an additional reference, [Laravel does install Xdebug as well in its dockerized …

Install PHP Xdebug debugger

---

config/waybar/config.jsonc

Icelandic was not being picked up by the clock on waybar, this issue contains more information.
https://github.com/Alexays/Waybar/issues/2694#issuecomment-1837118050

Add locale to the waybar clock format

---

bin/omarchy-cmd-audio-switch

- show visual feedback (device name, volume icon)
- prevents switching to the same sink, as it prevents a device from reacquiring the audio output when it reconnects
```
[ "$next_sink_name" != "$current_sink_name" ] && {
pactl set-default-sink "$next_sink_name"
}
```

add visual feedback for super + mute + fix

---

bin/omarchy-cmd-audio-switch

Filter audio sinks to include only available ports.
This fixes an issue where if the next sink is `not available` then the sink will not allow change even if there are other available sinks.

Update audio switch script to filter available sinks

---

applications/imv.desktop
migrations/1757273064.sh

When double clicking an image in Nautilus, my expectation is that I can navigate to the other images in the folder with the arrow keys.
This doesn't happen currently because the imv command receives only the filename as a parameter.
However, if we use:
`imv -n /myfolder/image.jpg /myfolder`
works becasue we're opening  the folder starting at the image given by the -n parameter.

Feed the image folder to the Image Viewer so the next/previous image navigation works

---

config/waybar/config.jsonc

Update waybar config with proper sized mute icon - same size as the two volume indicators. Current mute icon is smaller.
Mute icon after update:
Current mute icon:
Additionally, updates the wifi-off icon (which is also shown just before wifi connection is established) to an icon that matches the style of the remaining wifi icons. 
Current icon used: 󰖪
Updated icon: 󰤮

Update waybar config with proper sized mute icon and wifi-off icon in matching style

---

bin/omarchy-pkg-aur-install

Due to the recent [malicious packages found in the AUR](https://lists.archlinux.org/archives/list/aur-general@lists.archlinux.org/thread/7EZTJXLIAQLARQNTMEW2HBWZYE626IFJ/), it's good to check the PKGBUILD of the things you install to ensure nothing fishy is going on...
I binded that to `alt-b` (for "Build", as `alt-p` is already used). The thing is there's no (straightforward[^1]) way in fzf to toggle between different previews with one keybinding, so I opted for using `alt-B` to go back to the info (`-Siia`) preview.
Another alternative is using `preview` instead of `change-preview` in the `--bind`, making it so that when you select other package, it resets to the info preview.
Also note that the `tail -n +5` is for removing the header of the output of the yay command, as they are not …

Add option to show PKGBUILD in omarchy-pkg-aur-install

---

default/hypr/looknfeel.conf

Set hypr config [`cursor:hide_on_key_press`](https://wiki.hypr.land/Configuring/Variables/#cursor) to true by default, to hide the cursor when you start typing so it is not in the way. I find this a nice quality of life improvement as the cursor never gets in the way when I'm typing. It's also happens to be how macOS behaves.

Hide hyperland cursor while typing

---

themes/matte-black/ghostty.conf
themes/matte-black/vscode.json

I missed some important values in the Matte Black Ghostty theme (BG, FG, Cursor,...)

Fix Matte Black theme ghostty and vscode configs

---

bin/omarchy-menu

This PR adds Lutris to the installation menu in the gaming category, as mentioned in #1842. I’ll share more details in the issue on why I think it’s a good fit for Omarchy as a solution for non-Steam games.
I couldn’t figure out which icon font is used, so I left it without an icon for now. If someone knows, I’d be happy to add it so it matches the other options.
Fixes #1842

Add Lutris to Gaming installation menu

---

bin/omarchy-launch-webapp

This PR adds Helium browser to the supported browsers list in `omarchy-launch-webapp`.

Add Helium browser to supported browsers list in omarchy-launch-webapp

---

install/config/hardware/fix-apple-spi-keyboard.sh

Added:
MacBook 8,1
MacBook 9,1
MacBook 8,1 uses slightly different moduels from what I can tell, so I’ve added a case statment.  Please tweak as needed.

Add more Mac models to SPI keyboard support

---

bin/omarchy-cmd-screenrecord

Adding this PR as a fix for #1858 
The identified issue is when using the hyprctl bindings from default/hypr/bindings/utilities.conf
```
bindd = ALT, PRINT, Screen record a region, exec, omarchy-cmd-screenrecord region
bindd = ALT SHIFT, PRINT, Screen record a region with audio, exec, omarchy-cmd-screenrecord region audio
bindd = CTRL ALT, PRINT, Screen record display, exec, omarchy-cmd-screenrecord output
bindd = CTRL ALT SHIFT, PRINT, Screen record display with audio, exec, omarchy-cmd-screenrecord output audio
```
The call to omarchy-cmd-screenrecord differentiates output versus region as the first parameter used. A conditional is used to identify if the bash script caller is expecting a region or a display output for screen recording. The region handled this as a geometry, first …

Use output display or region geometry to record

---

bin/omarchy-menu

This PR clears the relaunch and restart state when restarting manually via the system menu.
Previously, the states only seemed to be cleared when using the ```omarchy-update-restart``` script, causing problems for users choosing to restart at a later time after an update.

feat: clear states when relaunching or rebooting from the system menu

---

bin/omarchy-menu-keybindings
config/hypr/bindings.conf
default/hypr/bindings.conf
default/hypr/bindings/tiling.conf
migrations/1755870033.sh

I started down this trail because I wanted to change what showed up in the SUPER+K menu as code:13 to numbers that were easier for me to read. Then my OCD kicked in an I wanted to standardize capitalization on the modifier keys. I am mifted by slash and return. I cannot get them to change in the menu. I could add a sed but figured it would not hurt to get other eyes on this first. Any ideas why those do not change in the menu with the changes in this PR?

Made keybindings menu a little more human readable

---

default/hypr/apps/steam.conf
install/omarchy-base.packages

Added gnome-disk-utility next to nautilus in install/omarchy-base-packages.
Since I installed i have been somewhat frustrated to see this error message when i clicked "Open in Disks" from Nautilus.
As I'm a Linux Newb, I assume i'm not the only one going through this.
Just today my question on the Omacom Discord was answered by @pooparoo and i figured the Powers That Be would be happy to have this installed from scratch also.

added gnome-disk-utility to base-packages

---

install/preflight/guard.sh

There are a handful of issues like #1861 #1534 #1138 and much more in discord. 
I think, for users, it will be helpful if we check for secure boot disabled before installing.

Check secure boot status before installing

---

bin/omarchy-launch-floating-terminal-with-presentation
default/hypr/apps/steam.conf

The presentation terminal's ASCII logo, displayed by 'omarchy-show-logo', would misalign if the user had a non-default font size set in their global Alacritty configuration.
This change fixes the issue by explicitly setting the font size to 9 for this specific terminal instance using the  flag.
This approach guarantees correct rendering of the logo without overriding the user's personal font preferences for their regular terminal sessions.
Before (at 14 font size):
After:

fix(presentation-terminal): Ensure consistent ASCII logo alignment

---

bin/omarchy-theme-set
bin/omarchy-theme-set-cursor
bin/omarchy-theme-set-vscode

Just copied `omarchy-theme-set-vscode`. Reading the `vscode.json` file in the themes because VSCode themes will work in Cursor and then omarchy-themes do not need to explicitly add `cursor.json`.

Theme support for Cursor

---

bin/omarchy-lock-screen

/bin/omarchy-launch-screensaver uses alacritty and /bin/omarchy-lock-screen uses $TERMINAL

Kill correct screensaver process when locking screen  

---

themes/osaka-jade/alacritty.toml
themes/osaka-jade/ghostty.conf
themes/osaka-jade/kitty.conf

Bright green color is hard to read on dark backgrounds. Adjusted color value for alacritty, ghostty, and kitty.
Bright green doesn't seem to be common, but it is used in the difftastic tool.

fix: update legibility of bright green color in Osaka Jade Theme

---

applications/nvim.desktop

The desktop entries doesn't expand any ennvars, so it needs to be executed via the shell.
Edit: It uses `omarchy-launch-editor` instead of `sh`.
resolves #1852

Fixes the nvim desktop entry exec command

---

config/ghostty/config

The custom `xterm-ghostty` TERM value in Ghostty can break terminal functionality when connecting via SSH to systems that lack the matching terminfo entry.
```
$ tmux ls
missing or unsuitable terminal: xterm-ghostty
```
To address this we need to enable [shell integration](https://github.com/ghostty-org/ghostty/issues/7608) feature.

Add SSH session integration for Ghostty

---

bin/omarchy-cmd-first-run
default/hypr/apps/steam.conf
install/first-run/dns-resolver.sh
install/preflight/first-run-mode.sh

On first run, symlink systemd-resolved's resolver into /etc/resolv.conf
* use first-run script due to chroot restrictions
* add to password-less sudo first-run commands
Matches migration 1754984623

Use systemd-resolved's stub resolver

---

config/alacritty/alacritty.toml

Implemented suggestion from #988 to add the config for alacritty to save to the clipboard instead of to the primary clipboard.

Make shift+insert paste from clipboard in Alacritty
