basecamp/omarchy

default/hypr/bindings.conf

This replicates macOS spotlight behavior when pressing the binding for a second time

Open and close wofi with the same binding

---

install/plymouth.sh

Updates the new plymouth feature with two more kernel cmdline detections for [UKI](https://wiki.archlinux.org/title/Unified_kernel_image):
* /etc/cmdline.d/*.conf
* /etc/kernel/cmdline

Adds two more kernel cmdline detections

---

bin/omarchy-show-keybindings
default/hypr/windows.conf

* Fix show keybindings for the new subdivided files by @dhh
* Fix nautilus image previews (`Space` when in the file manager) should float and center the preview by @dhh

Omarchy v1.3.2

---

config/waybar/config

Waybar supports auto-reloading when style changes ([man page](https://man.archlinux.org/man/waybar.5.en)).

Automatically reload waybar style on changes

---

config/waybar/config

The waybar config file has an indentation issue in the top level keys, this PR fixes it.

format(waybar): fix wrong indentation for config file

---

config/waybar/style.css
migrations/1752249974.sh
migrations/1752251002.sh
themes/catppuccin/waybar.css
themes/everforest/waybar.css
themes/gruvbox/waybar.css
themes/kanagawa/waybar.css
themes/matte-black/backgrounds.sh
themes/matte-black/waybar.css
themes/nord/waybar.css
themes/tokyo-night/waybar.css

- Use @define-color directive to define color variables for each theme (@foreground for text, @background for background-color)
- apply the color variables in the main theme config, making it more extensible
- make waybar elements more evenly spaced with consistent margin and padding values
- add migration to apply the above changes to existing users

Extensible, evenly spaced waybar styling

---

config/hypr/hyprland.conf
default/hypr/autostart.conf
default/hypr/bindings/utilities.conf

See here: https://wiki.hypr.land/Useful-Utilities/Systemd-start/#launching-applications-inside-session

use uwsm to properly wrap applications as systemd units

---

install/docker.sh
install/login.sh

The setup is failing, this fixes it

Setup is failing

---

config/waybar/style.css

Resolves #251. 
Added min width to prevent the shift when changing active workspaces.
https://github.com/user-attachments/assets/303f1886-a20c-4463-b9e9-4bcff2a87856

Fix Workspace Numbers Shift

---

default/walker/themes/dmenu_150.css
default/walker/themes/dmenu_250.css
default/walker/themes/keybindings.css

there is an extra `/` that should not be there

fix: walker css url

---

bin/omarchy
bin/omarchy-refresh-swayosd
bin/omarchy-theme-set
config/swayosd/config.toml
config/swayosd/style.css
migrations/1753224615.sh
themes/catppuccin-latte/swayosd.css
themes/catppuccin/swayosd.css
themes/everforest/swayosd.css
themes/gruvbox/swayosd.css
themes/kanagawa/swayosd.css
themes/matte-black/swayosd.css
themes/nord/swayosd.css
themes/rose-pine/swayosd.css
themes/tokyo-night/swayosd.css

Continues on where @mtk3d left off with #274. Added a default configuration and ported all the current themes.
@dhh

full swayosd integration

---

bin/omarchy
bin/omarchy-theme-update

Add theme update script

---

bin/omarchy-launch-screensaver
bin/omarchy-refresh-hypridle
config/hypr/hypridle.conf
migrations/1754136581.sh

Start screensaver after 1 minute. Ensure that it's not just killing itself when it does.

Start screensaver automatically

---

bin/omarchy-update
bin/omarchy-update-available
config/waybar/config.jsonc
default/hypr/windows.conf

Add a little icon next to the time when there's a new Omarchy version available. Clicking it will launch omarchy-update:

Show indicator if update is available

---

bin/omarchy-install-dev-env

through [php.new](https://php.new)

Add Laravel

---

bin/omarchy-menu
bin/omarchy-state
bin/omarchy-update
config/uwsm/env
default/bash/shell
migrations/1754680295.sh

Adds to the system path via UWSM. Also tested adding via proflile.d but that didn't get picked up everywhere, particularly by Walker whereas this does.
Fixes #557

Add ~/.local/share/omarchy/bin to systemwide PATH

---

bin/omarchy-install-dev-env
bin/omarchy-menu

Sorry on my dev environnement I have done this step earlier. Fix #624

Fix missing defaults PHP extensions to create Laravel Project

---

bin/omarchy-version
default/bash/aliases

As discussed in https://github.com/basecamp/omarchy/pull/562 (closed)
Using omarchy-command, instead. 
thanks

Omarchy-version command

---

bin/omarchy-menu

For reference the official OCaml logo + name

Use correct casing for OCaml menu item

---

install.sh

Hi! Was just installing Omarchy and with AUR misbehaving ran into problems. Thought this would be an, admittedly small, quality of life improvement.

Add QR code for discord link

---

install/config/hardware/nvidia.sh

Account for space between # and text for Nvidia multilib

---

bin/omarchy-install-docker-dbs

This PR replaces postgres 16 with 17 for development db installations. 17 has been out for almost a year now and 18 is just around the corner.
P.S. I got convinced to give it a try after attending the RailsWorld (:

Install Postgres 17

---

install.sh
install/config/hardware/intel.sh

Resolves https://github.com/basecamp/omarchy/issues/296
This detects if you have an Intel GPU during installation and installs the right video acceleration based on your GPU generation.

Install video acceleration for intel GPUs

---

bin/omarchy-install-dev-env

Added the zls - Zig's Language Server when installing the Zig from Install GUI menu.

Added ZLS - Zig's Language Server when installing Zig

---

config/ghostty/config

fix: ghostty config typos

---

install/config/hardware/fix-apple-spi-keyboard.sh

feat: Added MacBook10,1 to the fix-apple-spi-keyboard.sh

---

bin/omarchy-cmd-audio-switch

Possible resolution for #1695.

Fix for '(null)' display on AirPod source selection

---

config/hypr/input.conf
default/hypr/apps/steam.conf

Fix typo in comments in input.conf

---

bin/omarchy-install-docker-dbs
default/hypr/apps/steam.conf

Follow up to https://github.com/basecamp/omarchy/commit/e260d28f43d40de5f816a556b71ba479de74b728

Adjust database installation message to only one

---

bin/omarchy-menu
default/hypr/apps/steam.conf

I looked for it and didn't find it, so i added it. 
- I have added the AUR package of cursor-cli

Added Cursor CLI in Install > AI
